### PR TITLE
fix: updateAndFetch returning updated result

### LINKED ISSUE #456: updateAndFetch may not include the updated value.
Currently, running `updateAndFetch` that modifies what's being searched for will result in an empty result.

for example, running the following code will result in 0 matched value, because `bar` is set to true

```
const result = client.updateAndFetch({
  entityName: 'foo',
  where: {
     bar: false
  },
  operation: {
    $set: {
      bar: true
    }
  }
})
```

code of the cause can be found at `mongodb-client.ts` in the `mongoDbClient` package.

```
  async updateAndFetch<N extends Key<M>>(
    command: MultiUpdateCommand<N>
  ): Promise<EntityOf<M, N>[]> {
    const { entityName, where, operation } = command;
    const coll = this.conn.collection(entityName);
    await coll.updateMany(
      filterFindOperation(where),
      toMongoUpdateOperation(operation)
    );
    // FIXME: the result may be different from updated entities.
    return this.find({ entityName, where });
  }
```

### PR DESCRIPTION
**Pull request by Naturalclar**
fixes #456 

made updateAndFetch to get the id of results before hand, so that result can contain value of the updated result

also added test for updateAndGet, and updateAndFetch

### CODE REVIEW

File: modules/mongodb/src/mongodb-client.ts [hunk 1]
```diff
@@ -321,17 +323,30 @@ export class PhenylMongoDbClient<M extends GeneralEntityMap>
...
-    return this.find({ entityName, where });
+
+    const result = await this.getByIds({
+      entityName,
+      ids: findResult.map((entity) => entity.id),
+    });
+
+    // @ts-ignore
+    return result;
   }
```
Comment (Naturalclar) [inline modules/mongodb/src/mongodb-client.ts:350]: This is the part that changed

File: modules/mongodb/test/index.ts [hunk 2]
```diff
@@ -144,14 +144,44 @@ describe("MongoDBEntityClient", () => {
...
+        },
+        operation: {
+          $set: {
+            name: "Bob",
+          },
+        },
+      });
+      assert.deepStrictEqual(result.entities[0].name, "Bob");
+      assert.deepStrictEqual(result.n, 1);
+    });
```
Comment (Naturalclar) [inline modules/mongodb/test/index.ts:184]: These tests were added
